python src/data/clustering.py --prot_GE_file unmapped_GE/P0A6B4_4WR3_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A6I0_1KDO_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A6L2_1DHP_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A6T9_3A7L_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A763_2HUR_C_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A790_4CRZ_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A7J3_6XZ7_H_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A7N9_6XZ7_b_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0A8I5_3DXX_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0AA25_6LUR_D_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0ACP7_1QPZ_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0AD61_4YNG_C_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0ADY3_6XZ7_K_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P0AES0_2IO9_B_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P21599_6K0K_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P31142_1URH_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P37747_1I8T_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P45748_1HRU_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P60438_6PCR_N_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P60546_2ANB_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P61175_6XZ7_S_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/P65556_2FKB_A_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
python src/data/clustering.py --prot_GE_file unmapped_GE/Q46856_1OJ7_D_rebuilt_GE.txt --outpath unmapped_GE_clustered/ --organism Ecoli
