python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A6B4_4WR3_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A6E6_1AQT_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A6I0_1KDO_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A6L2_1DHP_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A6T9_3A7L_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A763_2HUR_C_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A790_4CRZ_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A7J3_6XZ7_H_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A7N9_6XZ7_b_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0A8I5_3DXX_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0AA25_6LUR_D_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0ACP7_1QPZ_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0AD61_4YNG_C_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0ADY3_6XZ7_K_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0ADZ0_6QUL_U_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0AES0_2IO9_B_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P0AG51_6XZ7_Z_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P21599_6K0K_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P31142_1URH_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P37747_1I8T_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P45748_1HRU_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P60438_6PCR_N_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P60546_2ANB_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P61175_6XZ7_S_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P65556_2FKB_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P77214_1ZEQ_X_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/P77754_6BIE_A_rebuilt.pdb
python src/data/gaussian_entanglement.py --PDB data/post_rebuilt/Q46856_1OJ7_D_rebuilt.pdb
